version: "3.8"

services:
  discovery:
    build: discovery-service
    ports:
      - "8761:8761"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  gateway:
    build: gateway-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - discovery
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: JavaBack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-db:/var/lib/redis/data
  identity:
    build: identity-service
    ports:
      - "8070:8070"
    restart: always
    depends_on:
      - discovery
      - redis
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  marketplace:
    build: marketplace-service
    ports:
      - "8090:8090"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/JavaBack'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: '1234'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    depends_on:
      - discovery
      - postgres

volumes:
  postgres-db:
  redis-db: