server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: books
          uri: http://localhost:8090
          predicates:
            - Path=/books/**
        - id: auth
          uri:
            http://localhost:8070
          predicates:
            - Path=/auth/**
