server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: books
          uri: lb://MARKETPLACE
          predicates:
            - Path=/books/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: lb://IDENTITY
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka